### ISSUE TITLE
Use MATLAB package namespace

### ISSUE THREAD

**Issue by singhbal-baljinder** [robotology/urdf2casadi-matlab#17]
Having a package namespace avoids name conflicts with other functions in the MATLAB path. See https://it.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html and https://github.com/robotology/urdf2casadi-matlab/issues/16#issuecomment-887344605.

**Comment by singhbal-baljinder** [comment]
I have started using a package/subpackage code organization in https://github.com/robotology/urdf2casadi-matlab/tree/package-namespace. All the tests in `testDynamicsAlgorithm.m` seem to pass well.

**Comment by singhbal-baljinder** [comment]
All the test in MATLAB are passing with the modifications introduced in https://github.com/robotology/urdf2casadi-matlab/commit/014730339804f8ff573d2dd36b602d8057f27ec0. The remaining tests are those related to Simulink.

**Comment by singhbal-baljinder** [comment]
Tests on `Simulink` are running with the modifications done in https://github.com/robotology/urdf2casadi-matlab/commit/9b9257f8be4f015f3d6247929d06edadb8346c40.

**Comment by traversaro** [comment]
As this modification are probably massive, it would probably make sense to tag the current version of the repo as v0.0.1 or something similar, and eventually add a CHANGELOG file (see https://keepachangelog.com/en/1.0.0/) to track the modifications in the repo (nothing to complex, just a sentence briefly discussing the changes).

**Comment by singhbal-baljinder** [comment]
> As this modification are probably massive, it would probably make sense to tag the current version of the repo as v0.0.1 or something similar, and eventually add a CHANGELOG file (see https://keepachangelog.com/en/1.0.0/) to track the modifications in the repo (nothing to complex, just a sentence briefly discussing the changes).

I was also thinking to start doing releases with changelogs.
