### ISSUE TITLE
Specify robot configuration space and constrains for which the library works

### ISSUE THREAD

**Issue by DanielePucci** [robotology/urdf2casadi-matlab#7]
Hi @singhbal-baljinder, if I am not wrong, the library works only for fixed-base, open-chain robots. If it is so, it would be nice to specify that in the [repo README](https://github.com/robotology/urdf2casadi-matlab/blob/master/README.md)

**Comment by traversaro** [comment]
Probably it is sufficient to add a few words in the initial sentence of the README, what do you think @singhbal-baljinder ?

**Comment by singhbal-baljinder** [comment]
@DanielePucci In #8  I have added some more info in the README, let me know if you think it is sufficient.

**Comment by DanielePucci** [comment]
LGTM! @singhbal-baljinder

**Comment by singhbal-baljinder** [comment]
> LGTM! @singhbal-baljinder

Perfect, then I'll close the issue.
